// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3cQCCVq90SZvcuwCXZ9ySWXppHPLA37g',
    appId: '1:641122017874:web:9d507690a0062a4872f58b',
    messagingSenderId: '641122017874',
    projectId: 'ecommence-d5506',
    authDomain: 'ecommence-d5506.firebaseapp.com',
    storageBucket: 'ecommence-d5506.firebasestorage.app',
    measurementId: 'G-8QEMRYYG43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO-yIVjUXdUNihQYNdSC4kPu_H1zSbZ1s',
    appId: '1:641122017874:android:a24b104b7644736272f58b',
    messagingSenderId: '641122017874',
    projectId: 'ecommence-d5506',
    storageBucket: 'ecommence-d5506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFxErA13I2ducgkMN38cW-mezDCNNNCT0',
    appId: '1:641122017874:ios:c5dba9f993ea738072f58b',
    messagingSenderId: '641122017874',
    projectId: 'ecommence-d5506',
    storageBucket: 'ecommence-d5506.firebasestorage.app',
    iosBundleId: 'com.example.loginSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFxErA13I2ducgkMN38cW-mezDCNNNCT0',
    appId: '1:641122017874:ios:c5dba9f993ea738072f58b',
    messagingSenderId: '641122017874',
    projectId: 'ecommence-d5506',
    storageBucket: 'ecommence-d5506.firebasestorage.app',
    iosBundleId: 'com.example.loginSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3cQCCVq90SZvcuwCXZ9ySWXppHPLA37g',
    appId: '1:641122017874:web:b9df86b345ad486372f58b',
    messagingSenderId: '641122017874',
    projectId: 'ecommence-d5506',
    authDomain: 'ecommence-d5506.firebaseapp.com',
    storageBucket: 'ecommence-d5506.firebasestorage.app',
    measurementId: 'G-LBL674P31W',
  );
}
